"""Updated Product and Category models#2

Revision ID: d2449d2a7e48
Revises: ffe99b6ad59a
Create Date: 2024-06-17 16:33:04.672143

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd2449d2a7e48'
down_revision: Union[str, None] = 'ffe99b6ad59a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('name', sa.String(), nullable=False))
    op.drop_constraint('categories_category_name_key', 'categories', type_='unique')
    op.create_unique_constraint(None, 'categories', ['name'])
    op.drop_column('categories', 'category_name')
    op.add_column('products', sa.Column('name', sa.String(), nullable=False))
    op.add_column('products', sa.Column('price', sa.Integer(), nullable=False))
    op.add_column('products', sa.Column('description', sa.String(), nullable=False))
    op.drop_column('products', 'product_price')
    op.drop_column('products', 'product_description')
    op.drop_column('products', 'product_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('product_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('products', sa.Column('product_description', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('products', sa.Column('product_price', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('products', 'description')
    op.drop_column('products', 'price')
    op.drop_column('products', 'name')
    op.add_column('categories', sa.Column('category_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'categories', type_='unique')
    op.create_unique_constraint('categories_category_name_key', 'categories', ['category_name'])
    op.drop_column('categories', 'name')
    # ### end Alembic commands ###
