"""Updated Products table

Revision ID: 9e926f6dbcc7
Revises: 535454bf7ef9
Create Date: 2024-02-16 14:00:51.384267

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e926f6dbcc7'
down_revision: Union[str, None] = '535454bf7ef9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('quantity', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'quantity')
    # ### end Alembic commands ###
