"""Updated

Revision ID: cc1385f87719
Revises: f063e2421702
Create Date: 2024-02-02 19:10:44.022155

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc1385f87719'
down_revision: Union[str, None] = 'f063e2421702'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('image_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'products', 'product_images', ['image_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_column('products', 'image_id')
    # ### end Alembic commands ###
