"""Update#3

Revision ID: 3d1b2bc381be
Revises: e7117501bc74
Create Date: 2024-02-03 16:55:13.653389

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d1b2bc381be'
down_revision: Union[str, None] = 'e7117501bc74'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_products_id'), 'products', ['id'], unique=False)
    op.drop_constraint('products_image_id_fkey', 'products', type_='foreignkey')
    op.drop_column('products', 'image_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('image_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('products_image_id_fkey', 'products', 'product_images', ['image_id'], ['id'])
    op.drop_index(op.f('ix_products_id'), table_name='products')
    # ### end Alembic commands ###
